#pragma once

typedef struct DwlDisplay DwlDisplay;

typedef enum DwlDisplayError {
    DWL_DISPLAY_ERROR_NO_XDG_RUNTIME_DIR,
    DWL_DISPLAY_ERROR_SOCKET_PERMISSION_DENIED,
    DWL_DISPLAY_ERROR_SOCKET_FD_LIMIT_REACHED,
    DWL_DISPLAY_ERROR_SOCKET_NO_MEM,
    DWL_DISPLAY_ERROR_CONNECT_PERMISSION_DENIED,
    DWL_DISPLAY_ERROR_CONNECT_WOULD_BLOCK,
    DWL_DISPLAY_ERROR_CONNECT_REFUSED,
    DWL_DISPLAY_ERROR_EPOLL_FD_LIMIT_REACHED,
    DWL_DISPLAY_ERROR_EPOLL_NO_MEM,
    DWL_DISPLAY_ERROR_EPOLL_PERMISSION_DENIED,
    DWL_DISPLAY_ERROR_UNKNOWN,
} DwlDisplayError;

DwlDisplay* dwl_display_connect(DwlDisplayError* out_error);

void dwl_display_disconnect(DwlDisplay* display);
