#pragma once

typedef enum DwlDisplayResult {
    DWL_DISPLAY_RESULT_NO_XDG_RUNTIME_DIR,
    DWL_DISPLAY_RESULT_SOCKET_PERMISSION_DENIED,
    DWL_DISPLAY_RESULT_SOCKET_FD_LIMIT_REACHED,
    DWL_DISPLAY_RESULT_SOCKET_NO_MEM,
    DWL_DISPLAY_RESULT_CONNECT_PERMISSION_DENIED,
    DWL_DISPLAY_RESULT_CONNECT_WOULD_BLOCK,
    DWL_DISPLAY_RESULT_CONNECT_REFUSED,
    DWL_DISPLAY_RESULT_EPOLL_FD_LIMIT_REACHED,
    DWL_DISPLAY_RESULT_EPOLL_NO_MEM,
    DWL_DISPLAY_RESULT_UNKNOWN,
    DWL_DISPLAY_RESULT_MAX_ENUM,
} DwlDisplayResult;
