#pragma once

typedef enum DisplayError {
    DISPLAY_ERROR_NONE,
    DISPLAY_ERROR_NO_XDG_RUNTIME_DIR,
    DISPLAY_ERROR_SOCKET_PERMISSION_DENIED,
    DISPLAY_ERROR_SOCKET_FD_LIMIT_REACHED,
    DISPLAY_ERROR_SOCKET_NO_MEM,
    DISPLAY_ERROR_CONNECT_PERMISSION_DENIED,
    DISPLAY_ERROR_CONNECT_WOULD_BLOCK,
    DISPLAY_ERROR_CONNECT_REFUSED,
    DISPLAY_ERROR_UNKNOWN,
    DISPLAY_ERROR_MAX_ENUM,
} DisplayError;
